apiVersion: v1
kind: ConfigMap
metadata:
  name: metaflow
data:
  METAFLOW_USER: chowda
  METAFLOW_SERVICE_URL: https://ahbt7svzbj.execute-api.us-east-1.amazonaws.com/api/
  METAFLOW_DEFAULT_DATASTORE: s3
  METAFLOW_DEFAULT_METADATA: service
  METAFLOW_DATASTORE_SYSROOT_S3: s3://clams-metaflow-metaflows3bucket-15l571qw7ao7p/metaflow
  METAFLOW_DATATOOLS_S3ROOT: s3://clams-metaflow-metaflows3bucket-15l571qw7ao7p/data
